[ourpfcfg]
oenable                        = "0              "
oserver                        = "               "
ouname                         = "               "
opasswd                        = "               "
oport                          = "12105          "
otimeout                       = "5              "
[xquncfg]
xqunenable                     = "1              "
xqunmode                       = "1              "
xqunuuid                       = "IIII-142493-FBBBC"
xqunpuship                     = "47.91.149.233  "
xqunsvraddr                    = "EKPNAUENAOIFSWSQLPAXPALNAYPGLXHXSUEGLKSZICHUPETAEEEHELHZIHLQPJAOPKEPSQIALUPALOHYLTEREKIDLKIEEOHUEIEJEEEMEN-$$"
# 