[extcfg]
eenable          = "0              "
eflag            = "0              "
einterval        = "50             "
[audioalarmcfg]
aaenable          = "0              "
aavalue           = "50             "
[ledcfg]
lstate           = "2              "
lenable          = "1            "
[upnpcfg]
uenable                        = "1              "
[tzcfg]
timezone         = "Asia/Hong_Kong "
dst_flag         = "0              "
[authcfg]
authflag         = "1              "
[timercfg]
reboot                  = "0                "
clock                   = "1                "
day                     = "1                "
breaktime               = "0                "
[sysinfo]
hardver          = "V1.0.0.1       "
softver          = "V1.0.0.1       "
lhstatus                       = "0              "
lhtimer                        = "0              "
[utils]
saradcb2cwitchdefaultvalue        = "300           "
saradcb2cswitchvalue              = "300           "
saradcc2bwitchdefaultvalue        = "500           "
saradcc2bswitchvalue              = "500           "
# 